### ISSUE TITLE
all example not able to run on  ubuntu-jammy-22.04-amd64-server on ec2 

### ISSUE THREAD

**Issue by sangam14** [deepfence/ebpfguard#52]
```
  Compiling clap v4.2.7
   Compiling ebpfguard-common v0.1.0 (/home/ubuntu/ebpfguard/ebpfguard-common)
   Compiling ebpfguard v0.1.0 (/home/ubuntu/ebpfguard/ebpfguard)
   Compiling file_open v0.1.0 (/home/ubuntu/ebpfguard/examples/file_open)
    Finished dev [unoptimized + debuginfo] target(s) in 34.36s
sudo: target/debug/examples/file_open: command not found
Failed to run `sudo -E target/debug/examples/file_open --path-to-deny /tmp/test`
```

let me known if I'm missing anything @noboruma @tomaszjonak

**Comment by tomaszjonak** [comment]
I assume you compiled via `RUST_LOG=info cargo xtask run --example file_open -- --path-to-deny /tmp/test`. This happens as we switched default build target to `x86_64-unknown-linux-musl` in https://github.com/deepfence/ebpfguard/pull/43. 

I noticed that docs don't mention need to install `x86_64-unknown-linux-musl` target as well. Gonna adjust examples and readme today.

**Comment by tomaszjonak** [comment]
@sangam14 fix merged. Let me know if you can run examples now. Heard from Thomas that there's a separate issue with actually executing protection. Please raise a separate issue for that.
